 const GET_SELLER = 'GET_SELLER';
 const GET_RATINGS = 'GET_RATINGS';
 const SHOW_DETAIL = 'SHOW_DETAIL';
 const SHOW_SHOP = 'SHOW_SHOP';
 const HIDE_SHOP = 'HIDE_SHOP';
 const HIDE_DETAIL = "HIDE_DETAIL"
 const GET_GOODS = "GET_GOODS";
 const INCREMENT = "INCREMENT";
 const DECREMENT = "DECREMENT";
 const SHOW_FOOD = 'SHOW_FOOD';
 const HIDE_FOOD = 'HIDE_FOOD';
 const FIXED_T = 'FIXED_T';
 const SELECTED_FOOD = 'SELECTED_FOOD';
 const CHANGE_TYPE = "CHANGE_TYPE";
 const TOGGLE = 'TOGGLE';
 const GET_RATIEARR = "GET_RATIEARR";
 const GET_FOODFILTER = "GET_FOODFILTER"
 export default {
     GET_SELLER,
     SHOW_DETAIL,
     HIDE_DETAIL,
     GET_GOODS,
     GET_RATINGS,
     DECREMENT,
     INCREMENT,
     HIDE_SHOP,
     SHOW_SHOP,
     SHOW_FOOD,
     HIDE_FOOD,
     FIXED_T,
     SELECTED_FOOD,
     CHANGE_TYPE,
     TOGGLE,
     GET_RATIEARR,
     GET_FOODFILTER


 }
